name: Documentation

on:
  push:
    branches:
      - master
      - actions/trigger/docs
    tags: '*'
  pull_request:

jobs:
  Documenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4
      - run: julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
      - run: julia -e 'using Run; Run.prepare_docs()'
      - run: julia -e 'using Run; Run.docs()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.SSH_KEY }}
        run: julia --project=docs docs/make.jl
